### ISSUE TITLE
Data Dump Export

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#101]
Extend #22 (PR #83) by allowing users to export all available data.

**Comment by johndiiorio** [comment]
This should be available to only admins and heavily rate-limited.

**Comment by huss** [comment]
I think we should discuss this. I can see where non-admin users might want
to do this. Also, it may make more sense to discuss the quantity of data
rather than how it is requested. I think we may have talked at at a team
meeting (much earlier) about having a warning if the size of the file was
larger than some specified value. Doing this would rate limit in a very
primitive way (just for that person and just how fast they can get
data/click) but it might be enough depending on how we do it and what is
needed. Just some thoughts.

All the best,
Steve

**Comment by huss** [comment]
We are about to add timezones to preferences (overall site setting) and to meters (overrides preferences). PR #508 fixes time shifts in graphs by setting everything to web browser local time but the DB does not have time zones with readings. When we dump raw data, the user might want the OED view of time zones (which is the relative time of the day) or the actual time zone that the meter data was collected in. Thus, we should add the meter time zone to the data we dump (maybe as a new column where repeated for as many reading for a given meter).

**Comment by huss** [comment]
There is now a design document for this and it is being done.
