### ISSUE TITLE
Determine need for user-selectable resolution

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#102]
Do any users need to be able to set their data resolution explicitly? If so, do they need to be able to set a _minimum_ resolution (e.g. at least 1 point per given time period) or an _exact_ resolution? How would that work?

**Comment by huss** [comment]
With the integration of Plotly the user can now scroll and zoom on data. This allows one to get higher resolution when the number of meter points is small enough (hundreds) and to get the day level resolution up to the maximum number graph points when there is more data. While this is not explicitly what this issue was asking for, it is believed it meets the needs of users. We also plan to add a feature to allow users to dump the raw meter data for the values shown on a graph. Given all of this, I am closing this issue.
