### ISSUE TITLE
Read non-Mamac meter data via Obvius

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#163]

**Comment by huss** [comment]
We want to be able to read many types of meters including BACnet and Modbus. If the values on the meter could be acquired then they could be added to OED via our API for new meter readings.

**Comment by NoraCodes** [comment]
Design decision made in meeting Fri 03-02-018: When pushes occur, if new meters are included, those meters will be immediately registered. Admins should be notified.

**Comment by huss** [comment]
We have decided to focus at this time on getting other meters read by using the Obvius suite. Some sites already have their hardware/software. Others might need to buy it but the price seemed reasonable for what it allows in terms of OED. The project also decided that the issues involved in directly reading many meter types (BACnet, Modbus) was not something we wanted to take on at this time. OED continues to remain open to incorporating other meters and system so OED can automatically read them. We have an API for accepting meter data. For example, we are working to allow sending CSV data. If you are interested in having other interfaces then please let us know and issues can be opened for these new types of devices/formats. Thus, this issue is being made specific to Obvius and new assignees to indicate it is in active development.

**Comment by huss** [comment]
We should try very hard to address #357 since Obvius data will be bringing in non-floating point data.
