### ISSUE TITLE
Add button to hide chart options

### ISSUE THREAD

**Issue by johndiiorio** [OpenEnergyDashboard/OED#244]
Similar to how options are hidden in a modal when the screen size shrinks, we should add the ability for the user to be able to do this.

This admin should be able to set the default of this behavior in the admin panel.

**Comment by LeoTindall** [comment]
I suggest that the admin also be able to decide that the modal is shown for non mobile users

**Comment by huss** [comment]
Just to clarify from the conversations with users about this, we want the chart link to honor this when when the link is used. The idea is to allow website links that focus more attention and real estate on the graphic since that is a common use case. It should also help with fixed monitors (no mouse) and on smaller screens.
