### ISSUE TITLE
Allow skipping missing data

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#267]
It should be possible to specify periods whose data is nonsensical and is to be ignored when graphing.

**Comment by huss** [comment]
With the Plotly integration the user can now zoom and shift the data graphed. While this does not do exactly what is asked, it does allow one to see reasonable graphs of sections with reasonable data. Also, we are planning to allow for editing of data. I think OED should show the data in the system or it should be modified. Hiding data could have unintended consequences. This request is mostly due to one meter type that seems to provide unrealistically high values at times. I think it would be better to deal with this through the data acquisition pipeline being developed that will warn the admin of values that exceed high/low thresholds. Someone else could provide a meter/vendor specific fix if they want but I don't think OED should do that (at least not at this time).
