### ISSUE TITLE
Allow renaming meters for display

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#352]
That is, meters should have a "real" name (name as reported by the hardware) and a display name. Display name should be the same as "real" name by default (or just use real name if display name is not set) but admins should be able to set the display name.

**Comment by huss** [comment]
The Obvius changes now include an identifier that is designed to serve this purpose. The graphic code needs to be changed to use this name. It isn't clear if groups need this as the name is assigned by the admin when created (unlike meters that are often automatically assigned). If we want to do for parallelism that is okay but we could also add a note to groups add comments about them. Note maps have notes so that would be similar.

**Comment by huss** [comment]
I thought about one more issue. The name of a meter is currently unique since it is used to look up the meter in several places. If we are going to use the identifier to identify meters (or groups) then it is likely we want to make it unique as well. This is a DB change in constraints on that column.

**Comment by huss** [comment]
Previous work made the identified unique in the DB. The new CSV/pipeline allow for updates so that is one way to change the name or identifier of a meter. Issue #644 address this directly so this issue is being closed.
