### ISSUE TITLE
Independent Migrations

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#365]
Each individual migration should have its own registered migration, primarily to support #160 . This may require rethinking the migrations system written in #306.

Specifically, it's bad to have all migrations between a version A and a version B in a migration called "A-B" because:
1. it is painful for developers to add and test migrations, since the database will think it is at version B even if the developer adds new SQL code to that migration
2. Failing to migrate can place the database in an unmigratable state because the database will be marked as being in version A despite some changes for B having been applied.

**Comment by buip** [comment]
I agree. I think we should rewrite the migration system. 

`Failing to migrate can place the database in an unmigratable state because the database will be marked as being in version A despite some changes for B having been applied.` 

This is not a big issue because the database will revert to its original state if it fails to migrate. I remember it's covered in the code

**Comment by buip** [comment]
I worked with Entity Framework in ASP.NET before and I think their logic of database migration is pretty cool.

**Comment by huss** [comment]
For similar reasons to issue #367, this is being closed.
