### ISSUE TITLE
Set default meters and groups

### ISSUE THREAD

**Issue by wendelap** [OpenEnergyDashboard/OED#384]
I imagine users will often be looking at certain meters or groups much more often than the rest. It'd be nice if they could set default meters and groups to show up when you first visit the page.

**Comment by huss** [comment]
The groups and meters can be searched to make finding one easier. It is also possible to do the chart link to have the page show certain meters and/or groups when the page loads. Since users do not have their own login, this would have to be an admin feature for everyone. Given this, I'm inclined to use the above two mechanisms unless sites ask for this.
