### ISSUE TITLE
Groups editing shows wrong name after cancellation

### ISSUE THREAD

**Issue by NoraCodes** [OpenEnergyDashboard/OED#415]
When you modify the name of a group, hit cancel, and then go to edit another group, it shows the previously entered name in place of meter's actual name. (previously #411)

**Comment by jameeters** [comment]
This is because hitting the cancel button no longer fires "change display mode" action that correctly handles the switch, and instead just pushes `/groups` to browser history. Anyone know what the goal of that change was?

Regardless, reverting to using the actions the way they're supposed to be used will fix this, and I bet it'll fix #416 as well.
