### ISSUE TITLE
Display disabled meters still show

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#494]
The meters page has a button to hide a meter that is then labeled Display Disabled. However, the meter still shows up on the main pages. This is going to be a bigger issue when Obvius is available since it often has many meter points that you don't want to show. While doing this it should be checked if Updates Enabled/Disabled is working correctly.

Setting for Milestone 0.7 Release but would be great if makes 0.6 Release.

**Comment by huss** [comment]
Note that issue #414 is a generalization of this and might be addressed at the same time.

**Comment by ak476519** [comment]
After checking with the Redux states, this is not essentially a bug. 

An admin can always fetch all of the meters available in the database, whereas a normal user can only fetch meters that are set to 'displayable'. We prefer to not filter out non-displayable meters at the home page, since it would be a good place to preview the data before making it public. 

So if a user has switched between logging in and out, they would have to refresh the page to see a view that matches their log-in status.

**Comment by huss** [comment]
So, this means that non-admin users that are working before the change in displayable will continue to be able to see those meters until they refresh the page to sync with the server. This is deemed acceptable as a rare event where they only see what they could already see for a little while.
