### ISSUE TITLE
Date ranges and what maps display

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#570]
Maps should honor the date ranges selected in the line graphic. This one is only really valuable once the circles are not a simple 4 weeks. Maybe we should consider the average over the time range of the line graph? Maybe some options as in compare for predefined time ranges?

Note the code currently uses the bar value and issue #475 discusses how this is not correct at this time. If it did it similarly to compare it might work better but that also can have issues.

**Comment by huss** [comment]
Another issue found is that maps use the last 4 week bar to get the value. If you change the date range via the slider on the line graphic then the map changes. It really is not the last 4 weeks in an absolute sense. Allowing the date range to vary like this may be okay, esp. once we choose what we are graphing in a more careful way.

**Comment by ngan-cassie** [comment]
I managed to get the map display the value according to line and bar graphs. Do you also need me to change the interface? Such as:
- Change "Bar Interval" => "Map Interval"
- Have a custom slider and toggle chart link for map (if possible)

I'll create a pull request so that you can see the code as well 

<img width="1075" alt="Screen Shot 2021-12-16 at 11 02 22 PM" src="https://user-images.githubusercontent.com/67377217/146491729-a7f7670a-ca50-4008-b222-3d02c057fdc4.png">

**Comment by huss** [comment]
As I commented in PR #687, bar and maps move together and it is okay. Other graphics do the same thing such as moving the slider on a line graphic changes the date ranges on other graphics. Thus, I think changing the label (and internationalizing it) on the map page is the preferred solution to use.

**Comment by huss** [comment]
The date ranges are honored indirectly because it uses the bar values. We may want to wait until we finalize what maps will show before this is addressed.

**Comment by huss** [comment]
The bars have been fixed up so the values are now better. Since maps use the last bar and it is now full width this is now okay. Given the user can select the time interval as in bars (day, week, 4 weeks) it seems this is fine until we decide that we want other values on maps.  Thus, this issue is considered closed.
