### ISSUE TITLE
bar custom slider not working

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#715]
### Describe the bug

The bar custom slider moves when you click day, week or 4 week buttons but you cannot drag to move it.

### To Reproduce

Click the "Toggle custom slider" button. You cannot more it from its current position.

### Expected behavior

The slider should move and set the length of each bar.

### Additional context

This works in v0.8.0. My first guess is that the recent package updates changed something but this has not been tested.

**Comment by jina2k** [comment]
I've tried multiple scenarios, trying to update packages, setting resolutions, changing it to use Handle, etc.

https://github.com/react-component/slider/issues/409
I've followed the above link for a direction in what to do, but most of these situations failed. I then tried to use Handle instead, this sort of worked, but it wasn't registering the changes made to the handle/slider, and it looked weird because there was both a slider and a handle.

Instead, I think this package in and of itself is an issue that hasn't been addressed, as well as having poor documentation where it makes it confusing to use. I'm thinking we should either replace this package with another one, or get rid of sliders in general, 
as rc-slider is only used in UIOptionsComponent.

Current alternative I am looking at is: https://chakra-ui.com/docs/form/slider
npm link is: https://www.npmjs.com/package/@chakra-ui/slider

Switching entirely a small problem would be a relatively easy fix, though I'm not sure if we really need a slider in the first place. If current users are only using it to display ie; 90 days to signify 1 quarter or 365 days to signify 1 year, then maybe we can provide buttons instead.

**Comment by jina2k** [comment]
I've recently tested chakra-ui/slider and have the same issue. Still not sure what the issue is currently.

**Comment by huss** [comment]
It does seem that rc-slider is not being heavily maintained. The proposed package is active and the license is okay. The only negative I see is that it is 202kB but the current one is 183kB so that isn't too much more. We might want to change in either case (if the slider works).

As for the question of if the slider is needed, the answer is it is nice but not essential. The goal was to allow users to pick the bar width in an arbitrary way. The button ones (day, week, 4 week) were convenient ones that were common. We could make it an input box (or something else) that would allow for other values. I'm open to ideas where we keep the basic functionality. I note the slider was sometimes hard to pick a specific value, esp. small ones so something else might be good. Also, I suspect this isn't heavily used (why you have to click to see it) so another, reasonable interface would be fine.

Note maps now have the buttons to pick the time frame. OED would like the have the slider (or something equivalent to what bar does) there too but that did not happen with the other change but is on the table to get done.
