### ISSUE TITLE
cannot select a meter in group creation

### ISSUE THREAD

**Issue by huss** [OpenEnergyDashboard/OED#717]
### Describe the bug

If you go to the group page and click to create a new group, you cannot select any meters to add to the group. It may be the case you cannot select a group but this is unknown as you cannot add one to see. Other meter menus seem to work fine.

### Expected behavior

This worked as of v0.8.0 but does not work now. It should work. It isn't yet known which merged PR caused the issue.

**Comment by jina2k** [comment]
I found that for this and issue #715 , the issue is with regards to getDerivedStateFromProps. Removing all 3 functions entirely, from UIOptionsComponent, SingleSelectComponent, and MultiSelectComponent, fixes the issues. 
I read this https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html again and it's best to remove it entirely and either control is solely through props or have it initialize with props and control it with state afterwards, along with a key. 
We can discuss this later in the upcoming meeting.
