### ISSUE TITLE
Read Mamac meters by the minute

### ISSUE THREAD

**Issue by LucasFares** [OpenEnergyDashboard/OED#75]
We currently read them by the hour but our system should be able to handle the extra data.

**Comment by huss** [comment]
When the new DB data draw is finalized we need to look at this, esp. given we have test data to see how it would work.

**Comment by huss** [comment]
Now that we are preparing to accept data from many sources (Obvius, CSV), we are testing non-hour based data because they often come in 15 or 20 minute intervals. To be careful, we are also checking that time intervals that are not evenly divisible into 24 hours work correctly given fast-pt. Thus, there should be no reason minute data will not work once all this testing is done. Having said that, we are less tied to Mamac meters (as we always planned) and we don't know of any interest in seeing data at this fast rate. While this should not be a hard change, I don't think we should do it until interest comes from users. For this reason I am closing this issue.
