### ISSUE TITLE
Add documentation to help new developers

### ISSUE THREAD

**Issue by DylanHNicolay** [OpenEnergyDashboard/OED#873]
### Is your feature request related to a problem? Please describe.
Adding documentation inside the development branch while OED is still in development may help new OED developers to better understand the codebase as well as get started faster.

### Describe the solution you'd like
I would like a folder to be created in the root directory that will contain pdf files that describe relevant parts of the codebase as well as links to relevant tools.

### Describe alternatives you've considered
A new page on the main OED page may be more accessable to people that are not yet working on the project but are interested in working with OED.

### Additional context
This is relevant to a midterm review for RCOS

**Comment by huss** [comment]
I don't know what others think but I'm not inclined to add this to the OED code repository. We have been adding developer information to that part of the OED website so that seems a more natural place for this. The README file does point to these pages.

I think better documentation is always good and welcome input. I just want to check if you have seen the [code organization page](https://openenergydashboard.github.io/developer/codeOrganization.html) and the [OED technologies page](https://openenergydashboard.github.io/developer/learningTechnologies.html). These might be helpful in forming new documentation and should be kept up to date with each other.
