### ISSUE TITLE
Bar stacking checkbox is obscured by bar interval slider label for low numbers

### ISSUE THREAD

**Issue by johndiiorio** [OpenEnergyDashboard/OED#96]

**Comment by LucasFares** [comment]
I edited the css to fix this (see image) but since there's no styleProp in React-rangeslider I can't make the changes stick. To fix this I could make another style sheet to override the default one or I could look into replacing React-rangeslider with with rc-slider. I'm leaning towards option 2. 
![rangeslider](https://user-images.githubusercontent.com/11081853/30612645-e8cec26e-9d4a-11e7-8a36-5abd180d0fa0.png)

**Comment by LeoTindall** [comment]
Proposition: make a "bar stacking" chart type radio button instead of the "bar stacking" checkbox.

**Comment by johndiiorio** [comment]
Implemented in #150, now fixed in the groupUI branch.
