### ISSUE TITLE
Move help website URL to .env or admin setting

### ISSUE THREAD

**Issue by spearec** [OpenEnergyDashboard/OED#974]
### Is your feature request related to a problem? Please describe.

Currently, the OED help base URL, which is used in TooltipHelpComponent to determine where to route users when they click help buttons.

```ts
// Normal/live URL for OED help pages
// Exported to HeaderButtonsComponent and LanguageSelectorComponent
export const BASE_URL = 'https://openenergydashboard.github.io/help/'
// Debug URL where need to put own GitHub ID before .github.io.
// This works if you have a fork of the web pages and setup your GitHub account to serve them up.
// export const BASE_URL = `https://xxx.github.io/OpenEnergyDashboard.github.io/help/`;
```

### Describe the solution you'd like

Instead of being stored in the code, this base URL should be stored in .env or should be an admin setting.
This would allow sites who want to host their own fork of OED help, such as in cases of poor long-distance internet connection, to easily change the URL without editing OED's code.

### Describe alternatives you've considered

Leave the URL in the code, until an OED user requests otherwise.

**Comment by huss** [comment]
To allow non-admins to control OED as much as possible, I would prefer to see this be a part of the admin user pages. The default value would be the standard location of OED help on the web (current value set by code).

Note that issue #890 will update the admin user pages for React hooks and a new look. It might be best to do this work after that is complete since it is low priority.

**Comment by Jake-Bodin** [comment]
I would like to work on this issue
